services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

  payload:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://mongo:27017/logankuzyk
    profiles:
      - prod

volumes:
  data:
