services:
  logankuzyk-website-payload:
    image: node:18-alpine
    ports:
      - '3000:3000' # Use a unique host port
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - logankuzyk-website-postgres
    env_file:
      - .env

  logankuzyk-website-postgres:
    image: postgres:17.0-alpine3.20
    ports:
      - '5432:5432' # Use a unique host port
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  data:
  node_modules:
